# Generated by Django 6.1.1 on 2026-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jutsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chakra_cost', models.IntegerField(default=20)),
                ('base_damage', models.IntegerField(default=35)),
                ('element', models.CharField(choices=[('FIRE', 'Katon (Fogo)'), ('WATER', 'Suiton (Água)'), ('WIND', 'Fuuton (Vento)'), ('LIGHTNING', 'Raiton (Trovão)'), ('EARTH', 'Doton (Terra)'), ('NEUTRAL', 'Taijutsu/Geral')], default='NEUTRAL', max_length=20)),
                ('is_healing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(choices=[('KONOHA', 'Folha'), ('AKATSUKI', 'Akatsuki'), ('SUNAGAKURE', 'Areia'), ('OTOGAKURE', 'Som')], default='KONOHA', max_length=20)),
                ('avatar_url', models.URLField(max_length=500)),
                ('max_hp', models.IntegerField(default=100)),
                ('max_chakra', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=20)),
                ('defense', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=15)),
                ('jutsus', models.ManyToManyField(related_name='ninjas', to='battle.jutsu')),
            ],
        ),
    ]
