# Generated by Django 6.1.1 on 2026-10-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ninja',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ninja',
            name='xp_to_next_level',
            field=models.IntegerField(default=100),
        ),
    ]
